version: '3'
services:

  # 配置mongodb
  mongodb:
    restart: always
    image: mongo:latest  # 指定docker desktop中的mongodb镜像名
    container_name: c_exphlp_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      exphlp_net:
        ipv4_address: 172.21.0.2  # 固定mongodb的ip 

  # 配置rabbitmq
  rabbitmq:
    restart: always
    image: rabbitmq:management  # 指定docker desktop中的rabbitmq镜像名
    container_name: c_exphlp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      exphlp_net:
        ipv4_address: 172.21.0.3  # 固定rabbitmq的ip

  # 配置webapp项目后端
  webapp:
    restart: always
    image: webapp:latest  # 指定docker desktop中的项目后端的镜像名
    container_name: c_exphlp_webapp
    ports:
      - "8080:8080"
    links:
      - mongodb
      - rabbitmq
    networks:
      exphlp_net:
        ipv4_address: 172.21.0.4  # 固定项目后端的ip

  # 配置exphlp_front项目前端
  exphlp_front:
    restart: always
    image: nginx:latest  # 指定docker desktop中的nginx的镜像名
    container_name: c_exphlp_vue_front
    ports:
      - "8086:8086"
    volumes:             # 数据卷挂载路径设置, 将本机目录映射到容器目录
      - "/D/nginx-docker/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/D/nginx-docker/conf/conf.d:/etc/nginx/conf.d"
      - "/D/nginx-docker/html:/usr/share/nginx/html"
      - "/D/nginx-docker/log:/var/log/nginx"
    # links:
    #   - webapp


networks:
  exphlp_net:
    ipam:
      config:
      - subnet: 172.21.0.0/24
