package fjnu.edu.auth;

public enum ErrorCode {
    INTERNAL_ERROR("INTERNAL_ERROR"),
    INVALID_ARGUMENT("INVALID_ARGUMENT"),

    AUTH_MISSING_TOKEN("AUTH_MISSING_TOKEN"),
    AUTH_INVALID_TOKEN("AUTH_INVALID_TOKEN"),
    AUTH_UNAUTHORIZED("AUTH_UNAUTHORIZED"),
    AUTH_BAD_CREDENTIAL_PAYLOAD("AUTH_BAD_CREDENTIAL_PAYLOAD"),
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS"),

    USER_ID_REQUIRED("USER_ID_REQUIRED"),
    USER_NAME_REQUIRED("USER_NAME_REQUIRED"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_FIELD_INVALID("USER_FIELD_INVALID"),
    USER_EMAIL_INVALID("USER_EMAIL_INVALID"),
    USER_MOBILE_INVALID("USER_MOBILE_INVALID"),
    USER_QQ_INVALID("USER_QQ_INVALID"),
    USER_RESET_PASSWORD_INVALID("USER_RESET_PASSWORD_INVALID"),

    PASSWORD_EMPTY("PASSWORD_EMPTY"),
    PASSWORD_LENGTH_INVALID("PASSWORD_LENGTH_INVALID"),
    PASSWORD_OLD_INVALID("PASSWORD_OLD_INVALID"),

    PLAN_ID_EMPTY("PLAN_ID_EMPTY"),
    PLAN_ID_FORMAT_INVALID("PLAN_ID_FORMAT_INVALID"),
    PLAN_NOT_FOUND("PLAN_NOT_FOUND"),

    AVATAR_FILE_EMPTY("AVATAR_FILE_EMPTY"),
    AVATAR_FILE_TYPE_INVALID("AVATAR_FILE_TYPE_INVALID"),
    AVATAR_PATH_INVALID("AVATAR_PATH_INVALID"),
    AVATAR_UPLOAD_FAILED("AVATAR_UPLOAD_FAILED");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}

