
spring:
  data:
    mongodb:
      uri: mongodb://user:123456@172.21.0.2:27017/expHlp?authSource=expHlp
      #uri: mongodb://user:123456@localhost:27017/expHlp?authSource=expHlp


#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host:
#    username: guest
#    password: guest
#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host:
#    username: user
#    password: 123456

  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-client-service